default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= Rails.application.credentials[:rails_max_threads] || 5 %>
  host:     <%= Rails.application.credentials[:postgres_host] || 'localhost' %>
  port:     <%= Rails.application.credentials[:postgres_port] || 5432 %>
  username: <%= Rails.application.credentials[:postgres_username] || 'tweet_storage' %>
  password: <%= Rails.application.credentials[:postgres_password] || 'tweet_storage' %>

production:
  <<: *default
  database: tweet_storage_production

development:
  <<: *default
  database: tweet_storage_development

test:
  <<: *default
  database: tweet_storage_test
