default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:     <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port:     <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'tweet_storage') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'tweet_storage') %>

production:
  <<: *default
  database: tweet_storage_production

development:
  <<: *default
  database: tweet_storage_development

test:
  <<: *default
  database: tweet_storage_test
